version: '3.7'

services:
  inspection:
    container_name: inspection
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    ports:
      - 3003:3000
 
volumes:
  node_modules:
