version: '3.7'

services:
  noticeboardpublic:
    container_name: noticeboardpublic
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    networks:
      - graphql
    ports:
      - 3001:3000

networks:
  graphql:
    external:
      name: graphql
